### ISSUE TITLE
Practica de predicados cuantificadores

### ISSUE THREAD

**Issue by irving1613** [SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-erick-ramos#1]
[practica de predicados equipo x.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-erick-ramos/files/7549082/practica.de.predicados.equipo.x.pdf)

**Comment by 71santiago7** [comment]
[PRACTICA 1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-erick-ramos/files/7549147/PRACTICA.1.pdf)

**Comment by 71santiago7** [comment]
[practica de predicados.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-erick-ramos/files/7549159/practica.de.predicados.pdf)

**Comment by saul19bautista** [comment]
calificación 23%
si cuenta con portada 25 puntos 

falto describir mas y los procedimientos 17 puntos

lista de figuras 20 puntos 

descripción de resultados, conclusión 15 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
